name: Build CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build english CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=cv_en -pretex=\def\LANG{en} -usepretex cv
      - name: Build spanish CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=cv_es -pretex=\def\LANG{es} -usepretex cv
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: latest
      #     release_name: CV
      #     draft: false
      #     prerelease: false
      - name: Upload English CV
        id: upload-release-asset-en
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/teofr/CV/releases/latest/assets{?name,label} 
          asset_path: ./cv_en/cv.pdf
          asset_name: cv_en.pdf
          asset_content_type: application/pdf
      - name: Upload Spanish CV
        id: upload-release-asset-es
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/teofr/CV/releases/latest/assets{?name,label}
          asset_path: ./cv_es/cv.pdf
          asset_name: cv_es.pdf
          asset_content_type: application/pdf
