name: Build CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build english CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -output-directory cv_en '\def \LANG {en} \input'
      - name: Build spanish CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -output-directory cv_es '\def \LANG {es} \input'
