name: Build CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build english CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=cv_en -pretex=\def\LANG{en} -usepretex cv
      - name: Build spanish CV
        uses: dante-ev/latex-action@master
        with:
          root_file: cv.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=cv_es -pretex="\def\LANG{es}" -usepretex cv
